FORMAT: 1A
HOST: http://supermodelapi.apiblueprint.org/

# Supermodel API
Supermodel is a developer tool for semantic modeling of cloud infrastructure through source code.

## Supermodel API Root []

### Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        [
            {
                "supermodel": "List of methods you can use with a model.",
                "published_at": "2015-08-05T08:40:51.620Z",
                "methods": [
                    {
                        "method": "checkout",
                        "description": "Check out a branch with the same name on all of the model repositories."
                    }, {
                        "method": "create",
                        "description": "Create a source code model based on the supermodel file."
                    }, {
                        "method": "delete",
                        "description": "Delete a source code model locally."
                    }, {
                        "method": "merge",
                        "description": "Git merge a branch on all repos to another branch on all repos."
                    }, {
                        "method": "pull",
                        "description": "Git pull all the repos in the model."
                    }, {
                        "method": "push",
                        "description": "Git push all repos to their remote branches."
                    }, {
                        "method": "show",
                        "description": "Show the supermodel on the command line."
                    }, {
                        "method": "status",
                        "description": "Git status for all the repos in the model."
                    }, {
                        "method": "sync",
                        "description": "Get a new version of the supermodel file from the remote."
                    }, {
                        "method": "update",
                        "description": "Update the local model with changes to the supermodel."
                    }
                ]
            }
        ]

### Model Operations [POST]

There are a variety of operations you can perform with a supermodel.

+ Request (application/json)

        {
            "checkout": "checkout the same branch for every repo in the model.",
            "branch_name": "branch name",
            "model_name": "model name"
        }

+ Response 201 (application/json)

    + Headers

            Location: /supermodel/2

    + Body

            {
                "model_name": "model name",
                "branch_name": "branch name",
                "git_response": [
                    {
                        "repo_name": "repo name",
                        "git_checkout": "checkout response"
                    }
                ]
            }
