FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# supermodel-api
Supermodel is a developer tool for semantic modelling of cloud infrastructure through source code.

## Supermodel Collection [/supermodel]

### List All Methods [GET]

+ Response 200 (application/json)

        [
            {
                "supermodel": "List methods you can use with a model.",
                "published_at": "2015-08-05T08:40:51.620Z",
                "methods": [
                    {
                        "method": "checkout",
                        "description": 2048
                    }, {
                        "method": "create",
                        "description": 1024
                    }, {
                        "method": "delete",
                        "description": 512
                    }, {
                        "method": "merge",
                        "description": 256
                    }
                ]
            }
        ]

### Operations for handling a source code model [POST]

There are a variety of operations you can perform with a supermodel.

+ Request (application/json)

        {
            "checkout": "checkout the same branch for every repo in the model.",
            "branch_name": "branch name",
            "model_name": "model name"
        }

+ Response 201 (application/json)

    + Headers

            Location: /supermodel/2

    + Body

            {
                "model_name": "model name",
                "branch_name": "branch name",
                "git_response": [
                    {
                        "repo_name": "repo name",
                        "git_checkout": "checkout response"
                    }
                ]
            }